# This config is for GPU training
Phase: 'test' #'train' or 'test'
Seed: 1
Device: 'cpu'
Metric: 'rmse'

Data:
  data_root: 'C:/Users/ku500817/Desktop/bathymetry/dataset/TrainingData/lidar'
  dataset:
    - 'dalma'
  span: 2 # diameter of the area surrounding the selected pixel point, for the data sampling
  batch_size: 16
  workers: 0
  elev_threshold: -0.1
  split:
    - 0.7 # train split
    - 0.3 # test split
  zscore_std: 2

Train:
   resume: False
   pre_trained_weights: 'weights/net.pth'
   start_epoch: 0
   num_epoch: 20
   print_freq: 1000
   save_file: "train_lidarnclip.csv"

Optimizer:
   lr: 0.001 # learning rate
   beta: 0.9 # momentum term of adam

Test:
  load_weights: True
  weight_dir: "C:/Users/ku500817/Desktop/bathymetry/code/TransBathy_results/net_lidarnclip_epoch20_span2.pth"
  save_test: True
  save_file: "test_rmse_global.csv"
  visualize: True
  visual_save_file: "test_visual_output_global.csv"

Model:
  tgt_len: 1
  num_features: 3 # equal to dim_model in transformer
  num_encoder_layers: 1
  num_decoder_layers: 0
  num_heads: 6
  dim_feedforward: 12 # equal to dim_feedforward in transformer
  dim_out: 1 # output dimension

Output_dir: "C:/Users/ku500817/Desktop/bathymetry/code/testonhost"

